import * as path from 'path';
import * as express from 'express';
import * as moment from 'moment';
import { AddressInfo } from 'net';
import { argv } from 'yargs';

var app = express();

var staticPath = path.join(__dirname, argv.client || "client");
console.log("Serving static files from " + staticPath);
app.use(express.static(staticPath));

process.on('uncaughtException', function (err) {
    console.error('Uncaught Exception: ' + err.message + '\r\n' + err.stack);
});

app.get('/api/example-rest-api', function (req, res) {
	res.json({ hello: 'computer'});
});

app.get('/test', function (req, res) {
	res.send("<p>This web page was generated by NodeJS.</p>\n<p>The current time is: " + moment().format('HH:mm:ss') + "</p>");	
});

var server = app.listen(process.env.PORT || 3000, () => {

    const addrInfo = server.address() as AddressInfo;
	const host = addrInfo.address;
	const port = addrInfo.port;
	console.log('Example app listening at http://%s:%s', host, port);
});
